name: diyetisyen_randevum
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  table_calendar: ^3.1.3
  intl: ^0.19.0
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.0
  flutter_local_notifications: ^16.3.2
  timezone: ^0.9.2
  firebase_messaging: ^14.7.21
  agora_rtc_engine: ^6.2.6
  permission_handler: ^10.4.3
  agora_token_service: ^0.1.2
  pdf: ^3.10.7
  path_provider: ^2.1.2
  open_file: ^3.3.2
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  provider: ^6.1.1
  fl_chart: ^0.66.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700